# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main # Pipeline runs automatically when code is pushed to the main branch

pool:
  vmImage: ubuntu-latest # Microsoft-hosted Ubuntu build agent where the pipeline executes

# Stage-1: Terraform Validate Stage
stages:
- stage: TerraformValidate
  jobs: # A job is a collection of tasks that run on the same build agent
    - job: TerraformValidateJob
      continueOnError: false # Stop the job and fail the pipeline if any task fails

      steps:

      - task: PublishPipelineArtifact@1 # Publish Terraform files as pipeline artifacts
        displayName: Publish Artifacts
        inputs:
          # Folder to be published as an artifact
          targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'

          # Artifact name visible in Azure DevOps pipeline run
          artifact: 'terraform-manifests-out'

          publishLocation: 'pipeline'

      - task: TerraformInstaller@0 # Install Terraform on the build agent
        displayName: Terraform Install
        inputs:
          terraformVersion: 'latest' # Downloads and installs the latest Terraform version

      - task: TerraformCLI@0 # Initialize Terraform and configure backend
        displayName: Terraform Init
        inputs:
          command: 'init'

          # Location of Terraform files
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'

          backendType: 'azurerm' # Use Azure Storage Account as Terraform backend

          # Azure DevOps Service Connection used to authenticate to Azure
          backendServiceArm: 'terraform-aks-azurerm-svc-con'

          # Resource Group containing the backend Storage Account
          backendAzureRmResourceGroupName: 'terraform-storage-rg'

          # Storage Account used to store Terraform state
          backendAzureRmStorageAccountName: 'terraformstatexlrwdrzs'

          # Blob Container inside Storage Account
          backendAzureRmContainerName: 'tfstatefiles'

          # Terraform state file name
          backendAzureRmKey: 'aks-base.tfstate'

          allowTelemetryCollection: false

      - task: TerraformCLI@0 # Validate Terraform configuration syntax and references
        displayName: Terraform Validate
        inputs:
          command: 'validate'

          # Execute validation in Terraform working directory
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'

          allowTelemetryCollection: false